const constants = {
  AUTH_USER: 'AUTH_USER',
  UNAUTH_USER: 'UNAUTH_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_MSG: 'AUTH_MSG',
  CLEAR_ERROR: 'CLEAR_ERROR',
  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  PROTECTED_TEST: 'PROTECTED_TEST',

  ADD_BARS: 'ADD_BARS',
  CLEAR_BARS: 'CLEAR_BARS',

  ADD_ERROR: 'ADD_ERROR',
  REMOVE_ERROR: 'REMOVE_ERROR',

  ADD_RESULTS: 'ADD_RESULTS',
  CLEAR_RESULTS: 'CLEAR_RESULTS',

  CHANGE_FETCHING: 'CHANGE_FETCHING',

};

export default constants;
